export type CatalogCategory =
  | 'libraries'
  | 'middleware'
  | 'tools'
  | 'adapters'
  | 'vector'
  | 'skills'
  | 'templates';

export interface CatalogEntry {
  id: string;
  category: CatalogCategory;
  title: string;
  packageName?: string;
  summary: string;
  docsPath?: string;
  examples?: string[];
  tags?: string[];
  aliases?: string[];
}

export const catalog: CatalogEntry[] = [
  {
    id: 'core',
    category: 'libraries',
    title: '@sisu-ai/core',
    packageName: '@sisu-ai/core',
    summary: 'Core agent runtime, context types, tools, and errors.',
    docsPath: 'packages/core/README.md',
    examples: ['examples/openai-hello/README.md'],
    tags: ['core', 'agent'],
    aliases: ['sisu-core'],
  },
  {
    id: 'rag-core',
    category: 'libraries',
    title: '@sisu-ai/rag-core',
    packageName: '@sisu-ai/rag-core',
    summary: 'Reusable backend-agnostic RAG mechanics for chunking, ingestion, and retrieval.',
    docsPath: 'packages/rag/core/README.md',
    examples: ['examples/openai-rag-chroma/README.md', 'examples/openai-rag-vectra/README.md'],
    tags: ['rag', 'library'],
    aliases: ['rag'],
  },
  {
    id: 'server',
    category: 'libraries',
    title: '@sisu-ai/server',
    packageName: '@sisu-ai/server',
    summary: 'HTTP server integration for Sisu agents.',
    docsPath: 'packages/server/README.md',
    examples: ['examples/openai-server/README.md'],
    tags: ['server', 'http'],
    aliases: ['http-server'],
  },
  {
    id: 'mw-rag',
    category: 'middleware',
    title: '@sisu-ai/mw-rag',
    packageName: '@sisu-ai/mw-rag',
    summary: 'Deterministic middleware-driven retrieval over a VectorStore.',
    docsPath: 'packages/middleware/rag/README.md',
    examples: ['examples/openai-rag-chroma/README.md', 'examples/openai-rag-vectra/README.md'],
    tags: ['rag', 'middleware', 'retrieval'],
    aliases: ['rag-middleware', 'middleware-rag'],
  },
  {
    id: 'mw-error-boundary',
    category: 'middleware',
    title: '@sisu-ai/mw-error-boundary',
    packageName: '@sisu-ai/mw-error-boundary',
    summary: 'Wraps middleware execution with structured error handling.',
    docsPath: 'packages/middleware/error-boundary/README.md',
    examples: ['examples/openai-error-handling/README.md'],
    tags: ['errors', 'safety'],
    aliases: ['error-boundary'],
  },
  {
    id: 'mw-guardrails',
    category: 'middleware',
    title: '@sisu-ai/mw-guardrails',
    packageName: '@sisu-ai/mw-guardrails',
    summary: 'Applies guardrails such as command limits and safety controls.',
    docsPath: 'packages/middleware/guardrails/README.md',
    examples: ['examples/openai-guardrails/README.md'],
    tags: ['guardrails', 'safety'],
    aliases: ['guardrails'],
  },
  {
    id: 'mw-conversation-buffer',
    category: 'middleware',
    title: '@sisu-ai/mw-conversation-buffer',
    packageName: '@sisu-ai/mw-conversation-buffer',
    summary: 'Converts input to messages and maintains bounded chat history.',
    docsPath: 'packages/middleware/conversation-buffer/README.md',
    examples: ['examples/openai-hello/README.md'],
    tags: ['messages', 'chat'],
    aliases: ['conversation-buffer'],
  },
  {
    id: 'mw-skills',
    category: 'middleware',
    title: '@sisu-ai/mw-skills',
    packageName: '@sisu-ai/mw-skills',
    summary: 'Loads filesystem or package-based skills into agents.',
    docsPath: 'packages/middleware/skills/README.md',
    examples: ['examples/openai-skills/README.md', 'examples/anthropic-skills/README.md'],
    tags: ['skills'],
    aliases: ['skills-middleware'],
  },
  {
    id: 'mw-tool-calling',
    category: 'middleware',
    title: '@sisu-ai/mw-tool-calling',
    packageName: '@sisu-ai/mw-tool-calling',
    summary: 'Runs the model tool loop for registered tools.',
    docsPath: 'packages/middleware/tool-calling/README.md',
    examples: ['examples/openai-weather/README.md'],
    tags: ['tools', 'function-calling'],
    aliases: ['tool-calling'],
  },
  {
    id: 'mw-register-tools',
    category: 'middleware',
    title: '@sisu-ai/mw-register-tools',
    packageName: '@sisu-ai/mw-register-tools',
    summary: 'Registers tool definitions into agent context.',
    docsPath: 'packages/middleware/register-tools/README.md',
    examples: ['examples/openai-weather/README.md'],
    tags: ['tools', 'registry'],
    aliases: ['register-tools'],
  },
  {
    id: 'mw-control-flow',
    category: 'middleware',
    title: '@sisu-ai/mw-control-flow',
    packageName: '@sisu-ai/mw-control-flow',
    summary: 'Sequence, branch, switch, loop, and graph-oriented control flow.',
    docsPath: 'packages/middleware/control-flow/README.md',
    examples: ['examples/openai-control-flow/README.md', 'examples/openai-graph/README.md'],
    tags: ['workflow', 'branching'],
    aliases: ['control-flow'],
  },
  {
    id: 'mw-trace-viewer',
    category: 'middleware',
    title: '@sisu-ai/mw-trace-viewer',
    packageName: '@sisu-ai/mw-trace-viewer',
    summary: 'Generates HTML traces for debugging agent execution.',
    docsPath: 'packages/middleware/trace-viewer/README.md',
    examples: ['examples/openai-hello/README.md'],
    tags: ['observability', 'tracing'],
    aliases: ['trace-viewer'],
  },
  {
    id: 'tool-aws-s3',
    category: 'tools',
    title: '@sisu-ai/tool-aws-s3',
    packageName: '@sisu-ai/tool-aws-s3',
    summary: 'AWS S3 access tool.',
    docsPath: 'packages/tools/aws-s3/README.md',
    examples: ['examples/openai-aws-s3/README.md'],
    tags: ['aws', 's3', 'storage'],
    aliases: ['aws-s3'],
  },
  {
    id: 'tool-azure-blob',
    category: 'tools',
    title: '@sisu-ai/tool-azure-blob',
    packageName: '@sisu-ai/tool-azure-blob',
    summary: 'Azure Blob Storage access tool.',
    docsPath: 'packages/tools/azure-blob/README.md',
    examples: ['examples/openai-azure-blob/README.md'],
    tags: ['azure', 'blob', 'storage'],
    aliases: ['azure-blob'],
  },
  {
    id: 'tool-extract-urls',
    category: 'tools',
    title: '@sisu-ai/tool-extract-urls',
    packageName: '@sisu-ai/tool-extract-urls',
    summary: 'Extracts URLs from free-form text.',
    docsPath: 'packages/tools/extract-urls/README.md',
    examples: ['examples/openai-extract-urls/README.md'],
    tags: ['urls', 'text'],
    aliases: ['extract-urls'],
  },
  {
    id: 'tool-github-projects',
    category: 'tools',
    title: '@sisu-ai/tool-github-projects',
    packageName: '@sisu-ai/tool-github-projects',
    summary: 'GitHub projects and repository operations tool.',
    docsPath: 'packages/tools/github-projects/README.md',
    examples: ['examples/openai-github-projects/README.md'],
    tags: ['github'],
    aliases: ['github-projects'],
  },
  {
    id: 'tool-rag',
    category: 'tools',
    title: '@sisu-ai/tool-rag',
    packageName: '@sisu-ai/tool-rag',
    summary: 'Model-facing retrieval and storage tools over backend-agnostic RAG mechanics.',
    docsPath: 'packages/tools/rag/README.md',
    examples: ['examples/openai-rag-chroma/README.md', 'examples/openai-rag-vectra/README.md'],
    tags: ['rag', 'retrieval', 'storage'],
    aliases: ['rag-tools', 'retrieveContext', 'storeContext'],
  },
  {
    id: 'tool-summarize-text',
    category: 'tools',
    title: '@sisu-ai/tool-summarize-text',
    packageName: '@sisu-ai/tool-summarize-text',
    summary: 'Summarizes long-form text content.',
    docsPath: 'packages/tools/summarize-text/README.md',
    tags: ['summary', 'text'],
    aliases: ['summarize-text'],
  },
  {
    id: 'tool-terminal',
    category: 'tools',
    title: '@sisu-ai/tool-terminal',
    packageName: '@sisu-ai/tool-terminal',
    summary: 'Terminal tool for shell command execution.',
    docsPath: 'packages/tools/terminal/README.md',
    examples: ['examples/openai-terminal/README.md'],
    tags: ['terminal', 'shell'],
    aliases: ['terminal'],
  },
  {
    id: 'tool-web-fetch',
    category: 'tools',
    title: '@sisu-ai/tool-web-fetch',
    packageName: '@sisu-ai/tool-web-fetch',
    summary: 'Fetches and returns web content.',
    docsPath: 'packages/tools/web-fetch/README.md',
    examples: ['examples/openai-web-fetch/README.md'],
    tags: ['web', 'http'],
    aliases: ['web-fetch'],
  },
  {
    id: 'tool-web-search-duckduckgo',
    category: 'tools',
    title: '@sisu-ai/tool-web-search-duckduckgo',
    packageName: '@sisu-ai/tool-web-search-duckduckgo',
    summary: 'DuckDuckGo web search tool.',
    docsPath: 'packages/tools/web-search-duckduckgo/README.md',
    examples: ['examples/openai-web-search/README.md', 'examples/ollama-web-search/README.md'],
    tags: ['search', 'web'],
    aliases: ['web-search-duckduckgo', 'duckduckgo'],
  },
  {
    id: 'tool-web-search-google',
    category: 'tools',
    title: '@sisu-ai/tool-web-search-google',
    packageName: '@sisu-ai/tool-web-search-google',
    summary: 'Google Custom Search tool.',
    docsPath: 'packages/tools/web-search-google/README.md',
    examples: ['examples/openai-web-search/README.md'],
    tags: ['search', 'google'],
    aliases: ['web-search-google', 'google-search'],
  },
  {
    id: 'tool-web-search-openai',
    category: 'tools',
    title: '@sisu-ai/tool-web-search-openai',
    packageName: '@sisu-ai/tool-web-search-openai',
    summary: 'OpenAI-backed web search tool.',
    docsPath: 'packages/tools/web-search-openai/README.md',
    examples: ['examples/openai-web-search/README.md'],
    tags: ['search', 'openai'],
    aliases: ['web-search-openai'],
  },
  {
    id: 'tool-wikipedia',
    category: 'tools',
    title: '@sisu-ai/tool-wikipedia',
    packageName: '@sisu-ai/tool-wikipedia',
    summary: 'Wikipedia lookup tool.',
    docsPath: 'packages/tools/wikipedia/README.md',
    examples: ['examples/openai-wikipedia/README.md'],
    tags: ['wikipedia', 'search'],
    aliases: ['wikipedia'],
  },
  {
    id: 'adapter-openai',
    category: 'adapters',
    title: '@sisu-ai/adapter-openai',
    packageName: '@sisu-ai/adapter-openai',
    summary: 'OpenAI-compatible chat and embeddings adapter.',
    docsPath: 'packages/adapters/openai/README.md',
    examples: ['examples/openai-hello/README.md'],
    tags: ['openai', 'llm', 'embeddings'],
    aliases: ['openai'],
  },
  {
    id: 'adapter-anthropic',
    category: 'adapters',
    title: '@sisu-ai/adapter-anthropic',
    packageName: '@sisu-ai/adapter-anthropic',
    summary: 'Anthropic chat adapter for Claude models.',
    docsPath: 'packages/adapters/anthropic/README.md',
    examples: ['examples/anthropic-hello/README.md'],
    tags: ['anthropic', 'claude'],
    aliases: ['anthropic'],
  },
  {
    id: 'adapter-ollama',
    category: 'adapters',
    title: '@sisu-ai/adapter-ollama',
    packageName: '@sisu-ai/adapter-ollama',
    summary: 'Local Ollama adapter for chat and generation.',
    docsPath: 'packages/adapters/ollama/README.md',
    examples: ['examples/ollama-hello/README.md'],
    tags: ['ollama', 'local'],
    aliases: ['ollama'],
  },
  {
    id: 'vector-core',
    category: 'vector',
    title: '@sisu-ai/vector-core',
    packageName: '@sisu-ai/vector-core',
    summary: 'Shared VectorStore contract and vector math utilities.',
    docsPath: 'packages/vector/core/README.md',
    examples: ['examples/openai-rag-vectra/README.md'],
    tags: ['vector', 'contract'],
    aliases: ['vectorstore', 'vector-store'],
  },
  {
    id: 'vector-chroma',
    category: 'vector',
    title: '@sisu-ai/vector-chroma',
    packageName: '@sisu-ai/vector-chroma',
    summary: 'Chroma-backed VectorStore adapter.',
    docsPath: 'packages/vector/chroma/README.md',
    examples: ['examples/openai-rag-chroma/README.md'],
    tags: ['vector', 'chroma', 'rag'],
    aliases: ['chroma'],
  },
  {
    id: 'vector-vectra',
    category: 'vector',
    title: '@sisu-ai/vector-vectra',
    packageName: '@sisu-ai/vector-vectra',
    summary: 'Local file-backed Vectra VectorStore adapter.',
    docsPath: 'packages/vector/vectra/README.md',
    examples: ['examples/openai-rag-vectra/README.md'],
    tags: ['vector', 'vectra', 'rag'],
    aliases: ['vectra'],
  },
  {
    id: 'skill-code-review',
    category: 'skills',
    title: '@sisu-ai/skill-code-review',
    packageName: '@sisu-ai/skill-code-review',
    summary: 'Packaged code review skill.',
    docsPath: 'packages/skills/skill-code-review/README.md',
    tags: ['skill', 'review'],
    aliases: ['code-review-skill'],
  },
  {
    id: 'skill-debug',
    category: 'skills',
    title: '@sisu-ai/skill-debug',
    packageName: '@sisu-ai/skill-debug',
    summary: 'Packaged debugging skill.',
    docsPath: 'packages/skills/skill-debug/README.md',
    tags: ['skill', 'debug'],
    aliases: ['debug-skill'],
  },
  {
    id: 'skill-deploy',
    category: 'skills',
    title: '@sisu-ai/skill-deploy',
    packageName: '@sisu-ai/skill-deploy',
    summary: 'Packaged deployment skill.',
    docsPath: 'packages/skills/skill-deploy/README.md',
    tags: ['skill', 'deploy'],
    aliases: ['deploy-skill'],
  },
  {
    id: 'skill-explain',
    category: 'skills',
    title: '@sisu-ai/skill-explain',
    packageName: '@sisu-ai/skill-explain',
    summary: 'Packaged explanation skill.',
    docsPath: 'packages/skills/skill-explain/README.md',
    tags: ['skill', 'explain'],
    aliases: ['explain-skill'],
  },
  {
    id: 'skill-repo-search',
    category: 'skills',
    title: '@sisu-ai/skill-repo-search',
    packageName: '@sisu-ai/skill-repo-search',
    summary: 'Packaged repository search skill.',
    docsPath: 'packages/skills/skill-repo-search/README.md',
    tags: ['skill', 'search'],
    aliases: ['repo-search-skill'],
  },
  {
    id: 'skill-test-gen',
    category: 'skills',
    title: '@sisu-ai/skill-test-gen',
    packageName: '@sisu-ai/skill-test-gen',
    summary: 'Packaged test generation skill.',
    docsPath: 'packages/skills/skill-test-gen/README.md',
    tags: ['skill', 'tests'],
    aliases: ['test-gen-skill'],
  },
  {
    id: 'skill-install',
    category: 'skills',
    title: '@sisu-ai/skill-install',
    packageName: '@sisu-ai/skill-install',
    summary: 'Interactive installer for the Sisu framework skill.',
    docsPath: 'packages/skills/skill-install/README.md',
    tags: ['skills', 'installer'],
    aliases: ['skill-installer'],
  },
  {
    id: 'chat-agent',
    category: 'templates',
    title: 'chat-agent',
    summary: 'Minimal conversational agent starter with tracing.',
    tags: ['template', 'chat'],
    aliases: ['chat'],
  },
  {
    id: 'cli-agent',
    category: 'templates',
    title: 'cli-agent',
    summary: 'Single-shot CLI agent starter that takes prompt input from argv.',
    tags: ['template', 'cli'],
    aliases: ['cli'],
  },
  {
    id: 'rag-agent',
    category: 'templates',
    title: 'rag-agent',
    summary: 'Local Vectra-backed RAG starter using rag-core and tool-rag.',
    tags: ['template', 'rag', 'vectra'],
    aliases: ['rag'],
  },
];

export const categories: CatalogCategory[] = [
  'libraries',
  'middleware',
  'tools',
  'adapters',
  'vector',
  'skills',
  'templates',
];
